/* 1 */
SHOW TABLES;

/* 2 */
SELECT * FROM ACTOR;
SELECT * FROM FILM;
SELECT * FROM CUSTOMER;

/* 3 */
SELECT TITLE FROM FILM;
SELECT NAME AS "Language" FROM LANGUAGE;
SELECT FIRST_NAME FROM STAFF;

/* 4 */
SELECT DISTINCT RELEASE_YEAR FROM FILM;

/* 5 */

SELECT COUNT(STORE_ID) AS "NUMBER OF STORES" FROM STORE;
SELECT COUNT(STAFF_ID) AS "NUMBER OF EMPLOYEES" FROM STAFF;
SELECT COUNT(INVENTORY_ID) AS "RENTALS AVAILABLE" FROM INVENTORY;
SELECT COUNT(RENTAL_ID) AS "RENTED" FROM RENTAL;
SELECT COUNT(DISTINCT LAST_NAME) AS "NUMBER OF UNIQUE LAST NAMES" FROM ACTOR;

/* 6 */
select * from film;

SELECT DISTINCT length, TITLE 
FROM FILM ORDER BY length desc 
limit 10;

/* 7 */

SELECT actor_id, first_name,last_name
FROM actor
WHERE first_name='SCARLETT';

/* BONUS */

SELECT title FROM film
WHERE title LIKE '%ARMAGEDDON%' AND length>100;

/* BONUS */

SELECT count(title) as "Movies with Behind the Scenes" FROM film
WHERE special_features LIKE '%Behind the Scenes%';